// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQLuAlKwLoETGqTRnnLKvjmPB08nU_yNM',
    appId: '1:881171704502:web:14ad5e59815f9fcf6b9417',
    messagingSenderId: '881171704502',
    projectId: 'iot-uni-17ac1',
    authDomain: 'iot-uni-17ac1.firebaseapp.com',
    databaseURL: 'https://iot-uni-17ac1-default-rtdb.firebaseio.com',
    storageBucket: 'iot-uni-17ac1.firebasestorage.app',
    measurementId: 'G-B3C52Z94B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjUcyZCQN7qjJJbtYRjgqZ-CvDIwLWpFQ',
    appId: '1:881171704502:android:7803001ee95ddb6d6b9417',
    messagingSenderId: '881171704502',
    projectId: 'iot-uni-17ac1',
    databaseURL: 'https://iot-uni-17ac1-default-rtdb.firebaseio.com',
    storageBucket: 'iot-uni-17ac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5eWLYuNwRX6rYh8xn4qbosL6qvUUR1Mo',
    appId: '1:881171704502:ios:20a1d17e97a755976b9417',
    messagingSenderId: '881171704502',
    projectId: 'iot-uni-17ac1',
    databaseURL: 'https://iot-uni-17ac1-default-rtdb.firebaseio.com',
    storageBucket: 'iot-uni-17ac1.firebasestorage.app',
    androidClientId: '881171704502-pef78argcq2kbsthj6t9532csejl9kkp.apps.googleusercontent.com',
    iosClientId: '881171704502-e3pcf9cfgufihie0cata0j4qugh57g51.apps.googleusercontent.com',
    iosBundleId: 'com.example.kemet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5eWLYuNwRX6rYh8xn4qbosL6qvUUR1Mo',
    appId: '1:881171704502:ios:20a1d17e97a755976b9417',
    messagingSenderId: '881171704502',
    projectId: 'iot-uni-17ac1',
    databaseURL: 'https://iot-uni-17ac1-default-rtdb.firebaseio.com',
    storageBucket: 'iot-uni-17ac1.firebasestorage.app',
    androidClientId: '881171704502-pef78argcq2kbsthj6t9532csejl9kkp.apps.googleusercontent.com',
    iosClientId: '881171704502-e3pcf9cfgufihie0cata0j4qugh57g51.apps.googleusercontent.com',
    iosBundleId: 'com.example.kemet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQLuAlKwLoETGqTRnnLKvjmPB08nU_yNM',
    appId: '1:881171704502:web:541db5e4fd4df6376b9417',
    messagingSenderId: '881171704502',
    projectId: 'iot-uni-17ac1',
    authDomain: 'iot-uni-17ac1.firebaseapp.com',
    databaseURL: 'https://iot-uni-17ac1-default-rtdb.firebaseio.com',
    storageBucket: 'iot-uni-17ac1.firebasestorage.app',
    measurementId: 'G-5JPFZQPW9M',
  );
}
